### ISSUE TITLE
FLAC support

### ISSUE THREAD

**Issue by futurevessel** [eugene-eeo/orchid#1]
Great going, any chance of FLAC support ?

**Comment by eugene-eeo** [comment]
Hi, personally I don't have any FLAC files since all of my music is mp3. However I don't see a reason why flac [can't be supported](https://godoc.org/github.com/faiface/beep/flac) so if you want to have a go at it you can make a PR, else I'll only add it when I feel like it.

**Comment by futurevessel** [comment]
Sounds good to me.
